spring.application.name=MoviesList
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/moviesdb
spring.security.user.name=Raul
spring.security.user.password=1115
spring.security.user.roles=ADMIN
tmdb.api.key=700a04d13824bdf540339de6e6f175d5
tmdb.api.url=https://api.themoviedb.org/3