spring.application.name=MoviesList
spring.data.mongodb.uri=mongodb://127.0.0.1:27017/moviesdb
spring.security.user.name=Raul
spring.security.user.password=1115
spring.security.user.roles=ADMIN
tmdb.api.key=700a04d13824bdf540339de6e6f175d5
tmdb.api.url=https://api.themoviedb.org/3
# JWT secret key
security.jwt.secret-key =myVerySecureSecretKeyThatIsAtLeast32CharactersLong123456789
security.jwt.expiration-time=3600000
#
# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=raulnicula2004@gmail.com
spring.mail.password=zrvl jway pxpn kwrz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.config.import=optional:file:.env[.properties]
spring.ai.google.genai.api-key=${GOOGLE_GENAI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash
spring.ai.google.genai.chat.options.temperature=0.5